-- Task graph for settings-ui-consistency-fix.
-- Schema: todos(id TEXT, title TEXT, description TEXT, status TEXT).
-- Allowed status: pending, in_progress, done, blocked.
-- todo_deps: (todo_id TEXT, depends_on TEXT).
INSERT INTO todos (id, title, description, status) VALUES
  ('sufx-caption-width-fix',
   'Fix caption preview desktop width (R-001 critical)',
   'Constrain caption preview pane to <=50% of max-w-5xl at desktop. Verifier: AC-001-a, AC-001-c. See CaptionProfileShared.tsx line ~188.',
   'pending'),
  ('sufx-caption-orientation',
   'Rebuild caption preview as horizontal/vertical designer (R-001)',
   'Replace the static creator image with an SVG designer matching eval/fixtures/caption-mock-h-and-w.png: arrow boundaries + center lines only. Radio toggle reads project state. Verifier: AC-001-b.',
   'pending'),
  ('sufx-caption-ssot',
   'Enforce caption sizing single source of truth (R-001)',
   'Ensure preview and export share the caption sizing policy; remove any duplicated frontend constants or create a shared src/lib/captions/ helper per BLUEPRINT R-001. Verifier: AC-001-d.',
   'pending'),
  ('sufx-export-twocol-layout',
   'Route Export rows through SettingContainer (R-002)',
   'Convert every Export row to SettingContainer (or matching two-column wrapper). Verifier: AC-002-a, AC-002-b. See src/components/settings/export/**.',
   'pending'),
  ('sufx-page-padding-std',
   'Normalize page padding/density to About reference (R-003)',
   'Extract About outer classes to src/components/settings/shared/pageLayout.ts and apply to Advanced/Models/Export/Post-process. Verifier: AC-003-a, AC-003-b.',
   'pending'),
  ('sufx-slider-keyboard',
   'Add RangeWithNumber component + migrate all sliders (R-004)',
   'New src/components/ui/RangeWithNumber.tsx with two-way sync; replace every raw input[type=range] in settings. Verifier: AC-004-a, AC-004-b.',
   'pending'),
  ('sufx-color-contrast-fix',
   'Replace low-contrast classes with existing tokens (R-005)',
   'Walk audit.json R-005-color-light-grey-on-white and swap offending classes to About-conformant tokens. Verifier: AC-005-a, AC-005-b.',
   'pending'),
  ('sufx-descriptions-batch',
   'Fill in description props where i18n copy exists (R-006)',
   'For each R-005-missing-description row, wire existing translation keys; emit audit-report-after/descoped.md for rows lacking copy. Verifier: AC-006-a, AC-006-b, AC-006-c.',
   'pending'),
  ('sufx-static-gates',
   'Run lint, build, translations gates (R-008)',
   'bun run lint; bun run build; bun run scripts/check-translations.ts. All exit 0. Verifier: AC-008-a.',
   'pending'),
  ('sufx-baseline-reaudit',
   'Re-run settings audit and assert cluster counts (R-007)',
   'pwsh scripts/audit-settings-ui.ps1 into features/settings-ui-consistency-fix/audit-report-after/. Assert critical=0 and the five targeted rule counts =0 per AC-007-b; descoped.md covers any missing-description remainder. Verifier: AC-007-a, AC-007-b, AC-007-c.',
   'pending'),
  ('sufx-liveapp-pass',
   'Live-app verification of caption preview + sliders (R-008)',
   'scripts/launch-toaster-monitored.ps1; navigate Captions, toggle horizontal/vertical, drag + type into sliders, confirm no overflow. Verifier: AC-008-b.',
   'pending'),
  ('sufx-qc',
   'QC: run coverage + tasks gates',
   'pwsh scripts/check-feature-coverage.ps1 -Feature settings-ui-consistency-fix and pwsh scripts/check-feature-tasks.ps1 -Feature settings-ui-consistency-fix; both exit 0.',
   'pending');

INSERT INTO todo_deps (todo_id, depends_on) VALUES
  ('sufx-caption-ssot', 'sufx-caption-width-fix'),
  ('sufx-caption-ssot', 'sufx-caption-orientation'),
  ('sufx-export-twocol-layout', 'sufx-page-padding-std'),
  ('sufx-descriptions-batch', 'sufx-page-padding-std'),
  ('sufx-static-gates', 'sufx-caption-ssot'),
  ('sufx-static-gates', 'sufx-export-twocol-layout'),
  ('sufx-static-gates', 'sufx-slider-keyboard'),
  ('sufx-static-gates', 'sufx-color-contrast-fix'),
  ('sufx-static-gates', 'sufx-descriptions-batch'),
  ('sufx-baseline-reaudit', 'sufx-static-gates'),
  ('sufx-liveapp-pass', 'sufx-baseline-reaudit'),
  ('sufx-qc', 'sufx-liveapp-pass');
