
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async changeTranslateToEnglishSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_translate_to_english_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e as string };
}
},
async changeSelectedLanguageSetting(language: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_selected_language_setting", { language }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e as string };
}
},
async changeDebugModeSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_debug_mode_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e as string };
}
},
async changeWordCorrectionThresholdSetting(threshold: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_word_correction_threshold_setting", { threshold }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e as string };
}
},
async updateCustomWords(words: string[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_custom_words", { words }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e as string };
}
},
async changeCustomFillerWordsSetting(words: string[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_custom_filler_words_setting", { words }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e as string };
}
},
async changeCaptionFontSizeSetting(size: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_caption_font_size_setting", { size }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e as string };
}
},
async changeCaptionBgColorSetting(color: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_caption_bg_color_setting", { color }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e as string };
}
},
async changeCaptionTextColorSetting(color: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_caption_text_color_setting", { color }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e as string };
}
},
async changeCaptionPositionSetting(position: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_caption_position_setting", { position }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e as string };
}
},
async changeCaptionFontFamilySetting(family: CaptionFontFamily) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_caption_font_family_setting", { family }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e as string };
}
},
async changeCaptionRadiusPxSetting(radius: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_caption_radius_px_setting", { radius }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e as string };
}
},
async changeCaptionPaddingXPxSetting(padding: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_caption_padding_x_px_setting", { padding }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e as string };
}
},
async changeCaptionPaddingYPxSetting(padding: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_caption_padding_y_px_setting", { padding }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e as string };
}
},
async changeCaptionMaxWidthPercentSetting(percent: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_caption_max_width_percent_setting", { percent }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e as string };
}
},
async changeLazyStreamCloseSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_lazy_stream_close_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e as string };
}
},
async changeNormalizeAudioSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_normalize_audio_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e as string };
}
},
async changeVadPrefilterEnabledSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_vad_prefilter_enabled_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e as string };
}
},
async changeVadRefineBoundariesSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_vad_refine_boundaries_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e as string };
}
},
/**
 * Update the export `loudness_target` setting (R-003 / AC-001-a).
 * 
 * Frontend sends the enum string ("off" / "podcast_-16" /
 * "streaming_-14"); the backend never receives a `loudnorm=...` filter
 * from TS — that is built only by
 * `managers::splice::loudness::build_loudnorm_filter`.
 */
async changeLoudnessTargetSetting(target: LoudnessTarget) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_loudness_target_setting", { target }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e as string };
}
},
async changeExportVolumeDbSetting(volumeDb: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_export_volume_db_setting", { volumeDb }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e as string };
}
},
async changeExportFadeInMsSetting(fadeInMs: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_export_fade_in_ms_setting", { fadeInMs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e as string };
}
},
async changeExportFadeOutMsSetting(fadeOutMs: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_export_fade_out_ms_setting", { fadeOutMs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e as string };
}
},
async changeAppLanguageSetting(language: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_app_language_setting", { language }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e as string };
}
},
async changeUpdateChecksSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_update_checks_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e as string };
}
},
async changeWhisperAcceleratorSetting(accelerator: WhisperAcceleratorSetting) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_whisper_accelerator_setting", { accelerator }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e as string };
}
},
async changeOrtAcceleratorSetting(accelerator: OrtAcceleratorSetting) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_ort_accelerator_setting", { accelerator }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e as string };
}
},
async changeWhisperGpuDevice(device: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_whisper_gpu_device", { device }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e as string };
}
},
async getAvailableAccelerators() : Promise<AvailableAccelerators> {
    return await TAURI_INVOKE("get_available_accelerators");
},
async triggerUpdateCheck() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("trigger_update_check") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e as string };
}
},
async showMainWindowCommand() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("show_main_window_command") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e as string };
}
},
async cancelOperation() : Promise<void> {
    await TAURI_INVOKE("cancel_operation");
},
async isPortable() : Promise<boolean> {
    return await TAURI_INVOKE("is_portable");
},
async getAppDirPath() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_app_dir_path") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e as string };
}
},
async getAppSettings() : Promise<Result<AppSettings, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_app_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e as string };
}
},
async getDefaultSettings() : Promise<Result<AppSettings, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_default_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e as string };
}
},
async getLogDirPath() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_log_dir_path") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e as string };
}
},
async setLogLevel(level: LogLevel) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_log_level", { level }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e as string };
}
},
async openRecordingsFolder() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_recordings_folder") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e as string };
}
},
async openLogDir() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_log_dir") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e as string };
}
},
async openAppDataDir() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_app_data_dir") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e as string };
}
},
async getAvailableModels() : Promise<Result<ModelInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_available_models") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e as string };
}
},
/**
 * Category-aware model list. Returns every entry when `category` is
 * `None`, or just the matching slice when specified. Used by the
 * unified models page + the deprecated `list_llm_models` shim.
 */
async getModels(category: ModelCategory | null) : Promise<Result<ModelInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_models", { category }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e as string };
}
},
async getModelInfo(modelId: string) : Promise<Result<ModelInfo | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_model_info", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e as string };
}
},
async downloadModel(modelId: string, category: ModelCategory | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("download_model", { modelId, category }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e as string };
}
},
async deleteModel(modelId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_model", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e as string };
}
},
async cancelDownload(modelId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_download", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e as string };
}
},
async setActiveModel(modelId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_active_model", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e as string };
}
},
async getCurrentModel() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_current_model") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e as string };
}
},
async getTranscriptionModelStatus() : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_transcription_model_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e as string };
}
},
async isModelLoading() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("is_model_loading") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e as string };
}
},
async hasAnyModelsAvailable() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("has_any_models_available") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e as string };
}
},
async hasAnyModelsOrDownloads() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("has_any_models_or_downloads") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e as string };
}
},
async getWindowsMicrophonePermissionStatus() : Promise<WindowsMicrophonePermissionStatus> {
    return await TAURI_INVOKE("get_windows_microphone_permission_status");
},
async openMicrophonePrivacySettings() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_microphone_privacy_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e as string };
}
},
async getAvailableMicrophones() : Promise<Result<AudioDevice[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_available_microphones") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e as string };
}
},
async getAvailableOutputDevices() : Promise<Result<AudioDevice[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_available_output_devices") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e as string };
}
},
async setSelectedOutputDevice(deviceName: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_selected_output_device", { deviceName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e as string };
}
},
async getSelectedOutputDevice() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_selected_output_device") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e as string };
}
},
async normalizePlaybackAudioContract() : Promise<Result<PlaybackAudioContract, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("normalize_playback_audio_contract") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e as string };
}
},
async editorSetWords(words: Word[]) : Promise<Word[]> {
    return await TAURI_INVOKE("editor_set_words", { words });
},
async editorGetWords() : Promise<Word[]> {
    return await TAURI_INVOKE("editor_get_words");
},
async editorDeleteWord(index: number) : Promise<boolean> {
    return await TAURI_INVOKE("editor_delete_word", { index });
},
async editorRestoreWord(index: number) : Promise<boolean> {
    return await TAURI_INVOKE("editor_restore_word", { index });
},
async editorDeleteRange(start: number, end: number) : Promise<boolean> {
    return await TAURI_INVOKE("editor_delete_range", { start, end });
},
async editorRestoreAll() : Promise<boolean> {
    return await TAURI_INVOKE("editor_restore_all");
},
async editorSplitWord(index: number, position: number) : Promise<boolean> {
    return await TAURI_INVOKE("editor_split_word", { index, position });
},
async editorSilenceWord(index: number) : Promise<boolean> {
    return await TAURI_INVOKE("editor_silence_word", { index });
},
async editorUndo() : Promise<boolean> {
    return await TAURI_INVOKE("editor_undo");
},
async editorRedo() : Promise<boolean> {
    return await TAURI_INVOKE("editor_redo");
},
async editorGetKeepSegments() : Promise<([number, number])[]> {
    return await TAURI_INVOKE("editor_get_keep_segments");
},
async editorGetTimingContract() : Promise<TimingContractSnapshot> {
    return await TAURI_INVOKE("editor_get_timing_contract");
},
async editorGetProjection() : Promise<EditorProjection> {
    return await TAURI_INVOKE("editor_get_projection");
},
async mediaImport(path: string) : Promise<Result<MediaInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("media_import", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e as string };
}
},
async mediaGetCurrent() : Promise<Result<MediaInfo | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("media_get_current") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e as string };
}
},
async mediaGetAssetUrl() : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("media_get_asset_url") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e as string };
}
},
async mediaClear() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("media_clear") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e as string };
}
},
async exportTranscript(format: ExportFormat, maxCharsPerLine: number | null, includeSilenced: boolean | null) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_transcript", { format, maxCharsPerLine, includeSilenced }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e as string };
}
},
async exportTranscriptToFile(format: ExportFormat, path: string, maxCharsPerLine: number | null, includeSilenced: boolean | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_transcript_to_file", { format, path, maxCharsPerLine, includeSilenced }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e as string };
}
},
/**
 * Return all caption segments with their time ranges.
 * 
 * Kept for callers that only need SRT/VTT-style text segments (one line
 * per segment, no geometry). The preview + export caption rendering path
 * uses `get_caption_blocks` which carries per-line wrap and pixel
 * geometry authoritative for both surfaces.
 */
async getCaptionSegments() : Promise<CaptionSegment[]> {
    return await TAURI_INVOKE("get_caption_segments");
},
/**
 * Compute laid-out caption blocks consumed verbatim by the live preview.
 * 
 * The blocks carry per-line wrapped text plus every geometry value in
 * video pixels, so the preview scales them by `rendered / frame_height`
 * and renders a visual match of the export. Pass
 * `TimelineDomain::Source` for preview over the un-edited video;
 * `TimelineDomain::Edited` remaps to the concatenated output clock.
 */
async getCaptionBlocks(domain: TimelineDomain) : Promise<CaptionBlock[]> {
    return await TAURI_INVOKE("get_caption_blocks", { domain });
},
/**
 * Transcribe any audio or video file and populate the editor with word-level results.
 * 
 * For WAV files, reads samples directly. For all other formats (MP4, MP3, etc.),
 * uses FFmpeg to extract audio to a temporary 16kHz mono WAV first.
 */
async transcribeMediaFile(path: string) : Promise<Result<Word[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("transcribe_media_file", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e as string };
}
},
/**
 * Generate waveform peaks from a WAV audio file.
 * 
 * Returns `peak_count` normalized peak values (0.0–1.0) suitable for rendering
 * a bar-chart waveform. Falls back gracefully if the file cannot be decoded.
 */
async generateWaveformPeaks(path: string, peakCount: number | null) : Promise<Result<number[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("generate_waveform_peaks", { path, peakCount }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e as string };
}
},
/**
 * Get the keep-segments (non-deleted contiguous regions) from the editor.
 */
async getKeepSegments() : Promise<Result<KeepSegment[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_keep_segments") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e as string };
}
},
/**
 * Generate an FFmpeg concat filter script from keep-segments.
 * 
 * This produces a filter_complex command that can be run with FFmpeg CLI
 * to trim and concatenate the kept portions of the source media.
 * 
 * Note: this diagnostic script reflects keep-segments only. Silenced words
 * (from `EditorState::get_silenced_ranges`) are applied inside the live
 * preview/export paths via a post-concat `volume=enable='between(...)'`
 * gate (see `silence_filter_chain`) and are intentionally not reproduced
 * here — the script is a debug aid, not a render-parity artifact.
 * 
 * Usage: `ffmpeg -i <input> -filter_complex "<output>" -map "[outv]" -map "[outa]" <output_file>`
 */
async generateFfmpegEditScript(inputPath: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("generate_ffmpeg_edit_script", { inputPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e as string };
}
},
/**
 * Map an edit-timeline position back to the source-media position.
 * 
 * When words are deleted, the edited timeline is shorter than the source.
 * This maps a position on the edit timeline to the corresponding source time.
 * 
 * Always drives the mapping from `canonical_keep_segments_for_media` — the
 * same function the preview render (`render_temp_preview_audio`) and export
 * use — so the cursor and the audio it's scrubbing over stay sample-aligned.
 * The previous default path routed through
 * `EditorState::map_edit_time_to_source_time`, which uses raw
 * legacy keep-segments and drifted against the rendered audio whenever the
 * two pipelines disagreed on seam placement. See splice-logic synthesis
 * report.
 */
async mapEditToSourceTime(editTimeUs: number) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("map_edit_to_source_time", { editTimeUs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e as string };
}
},
async invalidateTempPreviewCache(generationToken: string | null, sourceMediaFingerprint: string | null, reason: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("invalidate_temp_preview_cache", { generationToken, sourceMediaFingerprint, reason }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e as string };
}
},
/**
 * Render (or reuse) a temporary preview audio artifact for the current edit state.
 */
async renderTempPreviewAudio() : Promise<Result<PreviewRenderMetadata, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("render_temp_preview_audio") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e as string };
}
},
/**
 * Export the edited media by running FFmpeg with trim/atrim filters.
 * 
 * Uses the keep-segments from the editor to produce an output file
 * with deleted segments removed. Supports both audio-only and video+audio.
 * 
 * `format_override`, when `Some`, wins over `settings.export_format`
 * for this invocation only (PRD R-001 / AC-001-b). `None` preserves
 * today's behavior of consuming `settings.export_format`
 * (AC-001-c / AC-002-b). Default authority still lives in Settings →
 * Advanced → Export.
 */
async exportEditedMedia(inputPath: string, outputPath: string, burnCaptions: boolean | null, formatOverride: AudioExportFormat | null) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_edited_media", { inputPath, outputPath, burnCaptions, formatOverride }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e as string };
}
},
/**
 * List the export formats that make sense for a given source file
 * extension.
 * 
 * Frontend calls this when the Editor loads a project so the export
 * format picker can render source-type-aware options without
 * duplicating the video-extension set (PRD R-004 / AC-004-a,
 * AC-004-b). The payload carries each format's canonical extension
 * (with leading dot) so the save-dialog filter and suggested
 * filename stay aligned with backend `AudioExportFormat::extension()`
 * (AC-005-a, AC-005-b). Backend is the single source of truth
 * (AC-003-a).
 */
async listAllowedExportFormats(sourceExtension: string) : Promise<AllowedExportFormat[]> {
    return await TAURI_INVOKE("list_allowed_export_formats", { sourceExtension });
},
/**
 * Loudness preflight: render the post-edit audio (same keep-segments
 * + seam-fade chain that preview/export use) into PCM and run an EBU
 * R128 measurement against the selected target.
 * 
 * AGENTS.md "Single source of truth for dual-path logic": the
 * underlying measurement and target lookup live in
 * `managers::splice::loudness`; this command only orchestrates the
 * FFmpeg decode and forwards the buffer.
 * 
 * AC-002-a / AC-002-b / AC-002-c.
 */
async loudnessPreflight(target: LoudnessTarget) : Promise<Result<LoudnessPreflight, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("loudness_preflight", { target }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e as string };
}
},
async analyzeFillers(minPauseUs: number | null) : Promise<Result<FillerAnalysis, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("analyze_fillers", { minPauseUs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e as string };
}
},
/**
 * Auto-delete all detected filler words in the transcript.
 */
async deleteFillers() : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_fillers") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e as string };
}
},
/**
 * Delete all detected adjacent duplicate words in the transcript.
 */
async deleteDuplicates() : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_duplicates") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e as string };
}
},
/**
 * Silence all detected long pauses by marking adjacent words as silenced.
 */
async silencePauses(minPauseUs: number | null) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("silence_pauses", { minPauseUs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e as string };
}
},
/**
 * Trim long pauses by reducing dead-air gaps to a maximum duration.
 * 
 * Unlike `silence_pauses` (which marks words as silenced), this command
 * shifts timestamps so that gaps exceeding the threshold are capped at
 * 300 ms, effectively removing dead air from the timeline.
 */
async trimPauses(minPauseUs: number | null, maxGapUs: number | null) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("trim_pauses", { minPauseUs, maxGapUs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e as string };
}
},
/**
 * Tighten all inter-word gaps to a maximum target duration.
 * Shortens ALL gaps exceeding the target — creating a tighter pace.
 */
async tightenGaps(targetGapUs: number | null) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("tighten_gaps", { targetGapUs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e as string };
}
},
async cleanupAll(minPauseUs: number | null, maxGapUs: number | null) : Promise<Result<CleanupResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cleanup_all", { minPauseUs, maxGapUs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e as string };
}
},
/**
 * Collapse every adjacent repetition group in the current transcript
 * by keeping the **clearest** take and deleting the rest. Returns per-
 * group detail so the UI can highlight what was decided and why.
 * 
 * If no media is loaded or audio decode fails, the command refuses to
 * run rather than silently falling back to the positional rule. That
 * refusal is intentional — positional "keep the first" behavior is
 * still available via the legacy `delete_duplicates` command.
 */
async cleanupSmartDuplicates() : Promise<Result<SmartCleanupResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cleanup_smart_duplicates") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e as string };
}
},
/**
 * Save the current project to a .toaster file.
 */
async saveProject(path: string, name: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_project", { path, name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e as string };
}
},
/**
 * Load a .toaster project file and populate the editor + media state.
 */
async loadProject(path: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_project", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e as string };
}
},
/**
 * Read the effective caption profile for the given orientation.
 * 
 * Prefers project-level overrides; falls back to app-level settings.
 * Slice B R-005 / AC-005-a / AC-005-b.
 */
async getCaptionProfile(orientation: Orientation) : Promise<Result<CaptionProfile, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_caption_profile", { orientation }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e as string };
}
},
/**
 * Write a caption profile to either the app settings or the currently
 * open project. Slice B R-005 / AC-005-c / AC-005-d.
 */
async setCaptionProfile(orientation: Orientation, profile: CaptionProfile, scope: ProfileScope) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_caption_profile", { orientation, profile, scope }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e as string };
}
},
/**
 * Compute the authoritative [`CaptionLayout`] for the given orientation
 * + frame dimensions. Both the live-preview React code and the libass
 * export composer invoke this same function (directly here, or via
 * `CaptionLayoutConfig::from_profile` in the export path), so results
 * are byte-identical. Slice B R-004-a / AC-004-b.
 */
async getCaptionLayout(orientation: Orientation, videoDims: VideoDims) : Promise<Result<CaptionLayout, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_caption_layout", { orientation, videoDims }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e as string };
}
},
async setModelUnloadTimeout(timeout: ModelUnloadTimeout) : Promise<void> {
    await TAURI_INVOKE("set_model_unload_timeout", { timeout });
},
async getModelLoadStatus() : Promise<Result<ModelLoadStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_model_load_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e as string };
}
},
async unloadModelManually() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("unload_model_manually") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e as string };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * A single row in the allowed-formats payload returned to the
 * frontend. `extension` carries the leading dot (e.g. `.mp4`) to
 * match `AudioExportFormat::extension()`; frontend code substrings
 * the leading dot off before passing to save-dialog filters.
 */
export type AllowedExportFormat = { format: AudioExportFormat; extension: string }
export type AppSettings = { bindings?: Partial<{ [key in string]: ShortcutBinding }>; start_hidden?: boolean; update_checks_enabled?: boolean; selected_model?: string; selected_output_device?: string | null; preferred_output_sample_rate?: number; translate_to_english?: boolean; selected_language?: string; debug_mode?: boolean; log_level?: LogLevel; custom_words?: string[]; model_unload_timeout?: ModelUnloadTimeout; word_correction_threshold?: number; app_language?: string; 
/**
 * Master gate for the Experimental settings group. When `false`,
 * per-flag booleans still store whatever the user last set, but the
 * `is_experiment_enabled` getter (and the matching
 * `useExperiment` hook on the frontend) return `false` so no
 * experimental feature actually activates. Defence-in-depth:
 * stored values are preserved across master toggle flips so a
 * user's prior opt-in comes back when they re-enable the master.
 */
experimental_enabled?: boolean; lazy_stream_close?: boolean; custom_filler_words?: string[] | null; whisper_accelerator?: WhisperAcceleratorSetting; ort_accelerator?: OrtAcceleratorSetting; whisper_gpu_device?: number; normalize_audio_on_export?: boolean; vad_prefilter_enabled?: boolean; vad_refine_boundaries?: boolean; 
/**
 * Loudness normalization target for export. Single source of truth
 * for the `loudnorm` filter — see
 * `managers::splice::loudness::build_loudnorm_filter`. Frontend
 * only stores this enum and renders a Select; it MUST NOT
 * hand-build a `loudnorm=...` string. Legacy
 * `normalize_audio_on_export` migrates to `PodcastMinus16` via
 * `settings::migrate_loudness_setting`.
 */
loudness_target?: LoudnessTarget; export_volume_db?: number; export_fade_in_ms?: number; export_fade_out_ms?: number; caption_font_size?: number; caption_bg_color?: string; caption_text_color?: string; caption_position?: number; caption_font_family?: CaptionFontFamily; caption_radius_px?: number; caption_padding_x_px?: number; caption_padding_y_px?: number; caption_max_width_percent?: number; 
/**
 * Per-orientation caption profiles. Slice B single-source-of-truth
 * for caption geometry — preview and export both read through
 * `managers::captions::compute_caption_layout(&profile, dims)`.
 * The flat `caption_*` fields above are retained one release for
 * backward-compat; on first load `defaults::ensure_caption_defaults`
 * seeds this from those flat fields.
 */
caption_profiles?: CaptionProfileSet; 
/**
 * Idempotency latch for the flat-field → profiles migration. Once
 * true, `ensure_caption_defaults` is a no-op on subsequent loads.
 */
caption_profiles_was_migrated?: boolean; settings_version?: number }
export type AudioDevice = { index: string; name: string; is_default: boolean }
/**
 * User-facing export format. Default is `Mp4` (current behavior:
 * H.264 video + AAC audio in mp4). The four audio-only variants drop
 * the video stream (`-vn`) and re-mux the post-edit audio with the
 * codec / bitrate listed in `export_format_codec_map`.
 * 
 * Serialized lowercase per PRD R-001 / data model:
 * `"mp4" | "mp3" | "wav" | "m4a" | "opus"`.
 */
export type AudioExportFormat = "mp4" | "mov" | "mkv" | "mp3" | "wav" | "m4a" | "opus"
export type AvailableAccelerators = { whisper: string[]; ort: string[]; gpu_devices: GpuDeviceOption[] }
/**
 * Authoritative caption unit consumed verbatim by preview and export.
 */
export type CaptionBlock = { index: number; start_us: number; end_us: number; 
/**
 * Already-wrapped visual lines; render one per row.
 */
lines: string[]; 
/**
 * CSS font-family stack for the preview (export uses `font_ass_name`).
 */
font_css: string; 
/**
 * ASS `Fontname=` value for libass.
 */
font_ass_name: string; font_size_px: number; text_color: Rgba; background: Rgba; padding_x_px: number; padding_y_px: number; radius_px: number; 
/**
 * Distance from the bottom of the frame to the bottom edge of the
 * caption box, in video pixels.
 */
margin_v_px: number; 
/**
 * Pixel width of the widest line (glyph advance sum). Preview uses
 * this to size the pill to the text; export uses it to size the ASS
 * `\p1` rectangle.
 */
text_width_px: number; 
/**
 * Per-line box height in video pixels (includes leading).
 */
line_height_px: number; 
/**
 * Frame dimensions this layout was computed against; the preview
 * divides by these to scale to the rendered `<video>`.
 */
frame_width: number; frame_height: number }
/**
 * Font family choice for captions. The preview CSS and the exported ASS
 * both read from this enum so they stay in visual sync.
 */
export type CaptionFontFamily = "Inter" | "Roboto" | "SystemUi"
/**
 * Canonical per-video caption layout derived from a `CaptionProfile`
 * and the target video dimensions. Preview (`get_caption_layout`
 * Tauri command) and libass export BOTH call
 * [`compute_caption_layout`] with the same inputs — any divergence
 * surfaces as a `preview_and_export_layouts_are_byte_identical`
 * test failure (Slice B SSOT gate).
 * 
 * All values are in authoritative **video pixels**.
 */
export type CaptionLayout = { 
/**
 * Vertical margin — distance from the top of the frame to the
 * baseline anchor of the caption box, derived from
 * `profile.position` as a percentage of frame height.
 */
margin_v_px: number; 
/**
 * Horizontal margin — symmetric left/right gutter derived from
 * `profile.max_width_percent`.
 */
margin_h_px: number; 
/**
 * Caption box width in video pixels
 * (`frame_width * max_width_percent / 100`).
 */
box_width_px: number; font_size_px: number; padding_x_px: number; padding_y_px: number; radius_px: number; 
/**
 * Background color RGBA (u8 quad parsed from `bg_color` hex).
 */
bg_rgba: [number, number, number, number]; 
/**
 * Text color RGBA.
 */
fg_rgba: [number, number, number, number]; font_family: CaptionFontFamily; frame_width: number; frame_height: number }
/**
 * Per-orientation caption profile. Carries the 9 user-configurable
 * caption geometry fields that persist in settings and projects.
 * Preview and libass export both consume geometry derived from this
 * via `managers::captions::compute_caption_layout` — the single
 * source of truth for caption layout math (AGENTS.md, Slice B).
 */
export type CaptionProfile = { font_size: number; bg_color: string; text_color: string; position: number; font_family: CaptionFontFamily; radius_px: number; padding_x_px: number; padding_y_px: number; max_width_percent: number }
/**
 * Pair of caption profiles selected by orientation. Desktop is used
 * for landscape (width/height > 1.0), Mobile for portrait or square.
 */
export type CaptionProfileSet = { desktop: CaptionProfile; mobile: CaptionProfile }
/**
 * A caption segment for SRT/VTT output and live preview.
 */
export type CaptionSegment = { index: number; start_us: number; end_us: number; text: string }
/**
 * Combined iterative cleanup: delete fillers, then delete cascading
 * duplicates, then trim pauses — all in a single undo snapshot.
 * 
 * After deleting fillers, new duplicates may emerge (e.g., "the um the"
 * becomes "the the"). This command loops until no more fillers or
 * duplicates are found, then trims pauses.
 */
export type CleanupResult = { fillers_removed: number; duplicates_removed: number; pauses_trimmed: number; gaps_tightened: number; passes: number }
/**
 * Atomic frontend projection of editor state after a backend transaction.
 */
export type EditorProjection = { words: Word[]; timing_contract: TimingContractSnapshot }
export type EngineType = "Whisper" | "Parakeet" | "Moonshine" | "MoonshineStreaming" | "SenseVoice" | "GigaAM" | "Canary" | "Cohere"
export type ExportFormat = "Srt" | "Vtt" | "Script"
/**
 * Detect filler words, duplicates, and long pauses in the current transcript.
 * Runs iterative simulation: after marking fillers as deleted, re-scans for
 * cascading duplicates (e.g., "the um the" → "the the" after filler removal).
 * This ensures the reported counts match what `cleanup_all` would actually remove.
 */
export type FillerAnalysis = { filler_indices: number[]; 
/**
 * Each pause: (word_index_before_gap, gap_duration_us)
 */
pauses: PauseInfo[]; filler_count: number; pause_count: number; 
/**
 * Indices of the second word in each adjacent duplicate pair.
 */
duplicate_indices: number[]; duplicate_count: number }
export type GpuDeviceOption = { id: number; name: string; total_vram_mb: number }
/**
 * A keep-segment: contiguous non-deleted region of the source media.
 */
export type KeepSegment = { start_us: number; end_us: number }
export type LogLevel = "trace" | "debug" | "info" | "warn" | "error"
/**
 * Preflight DTO surfaced to the frontend. All fields are computed
 * here in Rust — the React side reads and formats them but performs
 * **no arithmetic** on LUFS / dBTP / LRA values (AGENTS.md
 * "Single source of truth for dual-path logic"; AC-006-a).
 */
export type LoudnessPreflight = { 
/**
 * Integrated loudness across the analyzed buffer, LUFS. May be
 * `f64::NEG_INFINITY` for silent input — formatters should detect
 * non-finite values.
 */
integrated_lufs: number; 
/**
 * True-peak across the analyzed buffer, dBTP (max across
 * channels). May be `f64::NEG_INFINITY` for silent input.
 */
true_peak_dbtp: number; 
/**
 * EBU R128 loudness range (LRA), in LU.
 */
lra: number; 
/**
 * The integrated-LUFS target for the selected `LoudnessTarget`,
 * or `None` when the target is `Off`.
 */
target_lufs: number | null; 
/**
 * `target_lufs - integrated_lufs` in LU when both are finite,
 * otherwise `None`. Computed in Rust so the frontend cannot
 * re-derive it (AC-006-a).
 */
delta_lu: number | null }
/**
 * User-facing loudness target enum. Single source of truth for the
 * `loudnorm` filter parameters used by the export pipeline; the
 * frontend only stores/sends this enum and never builds a filter
 * string itself (AGENTS.md "Single source of truth for dual-path
 * logic"). See `build_loudnorm_filter` for the mapping.
 */
export type LoudnessTarget = 
/**
 * No `loudnorm` filter is emitted; export passes audio through.
 */
"off" | 
/**
 * Podcast / broadcast preset: integrated -16 LUFS.
 */
"podcast_-16" | 
/**
 * Streaming preset (Spotify/YouTube-friendly): integrated -14 LUFS.
 */
"streaming_-14"
export type MediaInfo = { 
/**
 * Absolute path to the media file.
 */
path: string; 
/**
 * File name without directory.
 */
file_name: string; 
/**
 * File size in bytes.
 */
file_size: number; 
/**
 * Whether this is video or audio.
 */
media_type: MediaType; 
/**
 * File extension (lowercase).
 */
extension: string }
export type MediaType = "Video" | "Audio"
export type ModelCategory = "Transcription" | "System" | "VoiceActivityDetection"
export type ModelInfo = { id: string; name: string; description: string; filename: string; url: string | null; sha256: string | null; size_mb: number; is_downloaded: boolean; is_downloading: boolean; partial_size: number; is_directory: boolean; engine_type: EngineType; accuracy_score: number; speed_score: number; supports_translation: boolean; is_recommended: boolean; supported_languages: string[]; supports_language_selection: boolean; is_custom: boolean; category?: ModelCategory; 
/**
 * Optional transcription-specific metadata block.
 * Legacy JSON without this field deserializes as None.
 */
transcription_metadata?: TranscriptionMetadata | null }
export type ModelLoadStatus = { is_loaded: boolean; current_model: string | null }
export type ModelUnloadTimeout = "never" | "immediately" | "min_2" | "min_5" | "min_10" | "min_15" | "hour_1" | "sec_15"
/**
 * Orientation selector for caption commands. Auto-detection happens
 * in the frontend editor radio; the Tauri surface only exposes the
 * two concrete profiles.
 */
export type Orientation = "Desktop" | "Mobile"
export type OrtAcceleratorSetting = "auto" | "cpu" | "cuda" | "directml" | "rocm"
export type PauseInfo = { after_word_index: number; gap_duration_us: number }
export type PermissionAccess = "allowed" | "denied" | "unknown"
export type PlaybackAudioContract = { selected_output_device: string; selected_output_device_available: boolean; preferred_output_sample_rate: number; detected_output_sample_rate: number | null; normalized_output_sample_rate: number; mismatch_detected: boolean }
export type PreviewRenderMetadata= { status: PreviewRenderStatus; preview_file_path: string | null; preview_url_safe_path: string | null; source_media_fingerprint: string | null; edit_version: string; generation_token: string; cache_hit: boolean }
export type PreviewRenderStatus = "ready" | "no_segments" | "missing_media"
/**
 * Scope for `set_caption_profile` — whether the write lands on
 * `AppSettings` (user-default) or the currently-open `ProjectSettings`
 * (per-project override).
 */
export type ProfileScope = "App" | "Project"
export type Rgba = { r: number; g: number; b: number; a: number }
export type SecretMap = Partial<{ [key in string]: string }>
export type ShortcutBinding = { id: string; name: string; description: string; default_binding: string; current_binding: string }
export type SmartCleanupResult = { groups_collapsed: number; words_deleted: number; decisions: SmartGroupDecision[]; 
/**
 * Sample rate used when scoring (16000 when audio was available, 0
 * when the command ran without audio and refused to fall back).
 */
sample_rate: number }
/**
 * Per-group decision exposed to the UI.
 */
export type SmartGroupDecision = { 
/**
 * Lowercase, punctuation-stripped repeated token (e.g. "the").
 */
token: string; 
/**
 * Word indices that formed the repeat group, in transcript order.
 */
members: number[]; 
/**
 * Index (into the word list) chosen as the survivor.
 */
survivor_index: number; 
/**
 * Indices marked deleted by this decision.
 */
deleted_indices: number[]; 
/**
 * Articulation score of the survivor in `[0, 1]`.
 */
survivor_score: number; 
/**
 * Articulation score of every member, aligned with `members`.
 */
member_scores: number[] }
/**
 * Which time axis the caller wants timestamps in.
 * 
 * * `Source` — the original media clock. Used by the live preview, which
 * plays the un-concatenated source video.
 * * `Edited` — the concatenated output clock. Used by the export so the
 * burned-in captions land on the right video frames after cuts.
 */
export type TimelineDomain = "Source" | "Edited"
/**
 * Diagnostics snapshot for edit-time/source-time contract validation.
 */
export type TimingContractSnapshot = { 
/**
 * Monotonic revision incremented after each successful state mutation.
 */
timeline_revision: number; total_words: number; deleted_words: number; active_words: number; 
/**
 * Source-media bounds inferred from transcript words.
 */
source_start_us: number; source_end_us: number; 
/**
 * Total duration of all keep-segments (edited timeline duration).
 */
total_keep_duration_us: number; keep_segments: TimingSegment[]; 
/**
 * Keep-segments snapped to the configured playback frame grid.
 */
quantized_keep_segments: TimingSegment[]; quantization_fps_num: number; quantization_fps_den: number; 
/**
 * True when keep-segments satisfy ordering/coverage contract checks.
 */
keep_segments_valid: boolean; 
/**
 * Human-readable warning when a contract check fails.
 */
warning: string | null }
/**
 * A keep-segment represented in microseconds.
 */
export type TimingSegment = { start_us: number; end_us: number }
export type TranscriptionMetadata = { engine_type: EngineType; accuracy_score: number; speed_score: number; supports_translation: boolean; supports_language_selection: boolean; supported_languages: string[] }
/**
 * Video dimensions in pixels. Input to `compute_caption_layout`.
 */
export type VideoDims = { width: number; height: number }
export type WhisperAcceleratorSetting = "auto" | "cpu" | "gpu"
export type WindowsMicrophonePermissionStatus = { supported: boolean; overall_access: PermissionAccess; device_access: PermissionAccess; app_access: PermissionAccess; desktop_app_access: PermissionAccess }
export type Word = { text: string; 
/**
 * Start timestamp in microseconds.
 */
start_us: number; 
/**
 * End timestamp in microseconds.
 */
end_us: number; deleted: boolean; silenced: boolean; 
/**
 * Word confidence from transcription. -1.0 = unknown.
 */
confidence: number; 
/**
 * Speaker identifier. -1 = unknown.
 */
speaker_id: number }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}

void TAURI_CHANNEL;
void __makeEvents__;
