-- caption-profiles-persistence task graph
INSERT INTO todos (id, title, description, status) VALUES
 ('cpp-types', 'Add CaptionProfile + CaptionProfileSet', 'Add Rust structs with specta::Type + default helpers in settings/types.rs and defaults.rs. Defaults per BLUEPRINT: desktop matches current flat defaults; mobile differs on font_size/position/max_width/radius/padding. Cargo tests AC-001-a/b/c.', 'pending'),
 ('cpp-app-migration', 'AppSettings.caption_profiles + migration', 'Add caption_profiles field (with was_migrated latch). ensure_caption_defaults seeds both profiles from old flat fields on first load. Flat fields stay #[deprecated]. Cargo tests AC-002-a/b/c.', 'pending'),
 ('cpp-project-schema', 'ProjectSettings.caption_profiles + version bump', 'Add Option<CaptionProfileSet>. Bump PROJECT_VERSION to 1.1.0. Backward-compat test loads a v1.0.0 fixture. Cargo tests AC-003-a/b/c, AC-008-a. Commit fixture at features/caption-profiles-persistence/fixtures/project_v1_0_0.toaster.', 'pending'),
 ('cpp-layout-helper', 'compute_caption_layout SSOT helper', 'Create src-tauri/src/managers/captions/mod.rs + layout.rs. Pure function per BLUEPRINT. Golden JSON fixtures for 1920x1080 desktop and 1080x1920 mobile. Cargo test AC-004-a.', 'pending'),
 ('cpp-export-wire', 'Wire export path through compute_caption_layout', 'Replace hardcoded math in export::ass composer with compute_caption_layout. Existing export tests must stay green.', 'pending'),
 ('cpp-commands', 'Tauri commands for profile+layout', 'Add get_caption_profile, set_caption_profile(scope), get_caption_layout. Wire into lib.rs handlers. Cargo tests AC-005-a/b/c/d.', 'pending'),
 ('cpp-parity-test', 'Preview↔export byte-identical test', 'Cargo test AC-004-b: calls the command + the export composer with same inputs; asserts equal CaptionLayout. This is the SSOT gate.', 'pending'),
 ('cpp-ui-split', 'Split CaptionSettings into tabs', 'Create CaptionDesktopTab.tsx, CaptionMobileTab.tsx, CaptionProfileShared.tsx. Thin shell CaptionSettings.tsx with tab control. Each file <800 LOC. AC-007-a/b.', 'pending'),
 ('cpp-preview-hook', 'useCaptionLayout hook + CaptionMockFrame layout prop', 'Hook calls get_caption_layout. CaptionMockFrame accepts optional layout prop; without it, falls back to Slice A schematic rendering.', 'pending'),
 ('cpp-editor-radio', 'Orientation radio in editor', 'src/components/editor/CaptionOrientationRadio.tsx with Desktop|Mobile|Auto. Auto derives from video_dims. Ephemeral React state. Live-QC AC-006-a/b/c.', 'pending'),
 ('cpp-dup-check', 'Prevent duplicated position math', 'gate-ripgrep-absent assertion that no caption position/margin math exists outside managers/captions/layout.rs. AC-004-c.', 'pending'),
 ('cpp-i18n', 'i18n across 20 locales', 'Add keys for Desktop/Mobile/Auto, profile tabs, radio. bun run scripts/check-translations.ts exit 0. AC-009-a/b.', 'pending'),
 ('cpp-static-gates', 'Static gates', 'gate-lint, gate-tsc, gate-cargo-check-lib, cargo test captions, check-translations. AC-011-a/b/c/d.', 'pending'),
 ('cpp-precision', 'Precision + boundary evals', 'transcript-precision-eval + audio-boundary-eval skills run. AC-010-a/b.', 'pending'),
 ('cpp-live-qc', 'Live-app QC', 'launch-toaster-monitored -ObservationSeconds 240. AC-006, AC-007-c, AC-008-b, AC-012-a. Record in journal.md.', 'pending');

INSERT INTO todo_deps (todo_id, depends_on) VALUES
 ('cpp-app-migration', 'cpp-types'),
 ('cpp-project-schema', 'cpp-types'),
 ('cpp-layout-helper', 'cpp-types'),
 ('cpp-export-wire', 'cpp-layout-helper'),
 ('cpp-commands', 'cpp-app-migration'),
 ('cpp-commands', 'cpp-project-schema'),
 ('cpp-commands', 'cpp-layout-helper'),
 ('cpp-parity-test', 'cpp-export-wire'),
 ('cpp-parity-test', 'cpp-commands'),
 ('cpp-ui-split', 'cpp-app-migration'),
 ('cpp-preview-hook', 'cpp-commands'),
 ('cpp-editor-radio', 'cpp-preview-hook'),
 ('cpp-dup-check', 'cpp-layout-helper'),
 ('cpp-i18n', 'cpp-ui-split'),
 ('cpp-i18n', 'cpp-editor-radio'),
 ('cpp-static-gates', 'cpp-parity-test'),
 ('cpp-static-gates', 'cpp-ui-split'),
 ('cpp-static-gates', 'cpp-editor-radio'),
 ('cpp-static-gates', 'cpp-i18n'),
 ('cpp-static-gates', 'cpp-dup-check'),
 ('cpp-precision', 'cpp-static-gates'),
 ('cpp-live-qc', 'cpp-static-gates'),
 ('cpp-live-qc', 'cpp-precision');
